# Generated by Django 5.1.6 on 2025-02-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "contractual_pr",
                    models.FloatField(help_text="Contractual Performance Ratio (%)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeteoStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("installation_date", models.DateField()),
                (
                    "data_log",
                    models.FileField(blank=True, null=True, upload_to="meteo_logs/"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meteo_stations",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_number", models.CharField(max_length=100)),
                ("capacity_kwp", models.FloatField(help_text="Rated capacity in kWp")),
                ("installation_date", models.DateField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonalPRMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("SPR", "Spring"),
                            ("SUM", "Summer"),
                            ("AUT", "Autumn"),
                            ("WIN", "Winter"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "measured_pr",
                    models.FloatField(help_text="Measured Performance Ratio (%)"),
                ),
                (
                    "difference",
                    models.FloatField(
                        blank=True,
                        help_text="Measured PR minus contractual PR",
                        null=True,
                    ),
                ),
                ("measured_date", models.DateField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pr_metrics",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                ("installed_on", models.DateField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trackers",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
